### ISSUE TITLE
Open source interactive visualizer

### ISSUE THREAD

**Issue by CryogenicPlanet** [githubocto/repo-visualizer#20]
Hey it would be great if you could open source the interactive visualizer https://octo-repo-visualization.vercel.app/?repo=paperjs%2Fpaper.js

If that is not possible, at least adding support for private repos with Access tokens would be nice

Another idea here is this repo could deploy an interactive version of the visualizer on gh pages so we can get that on each PR rather than the static svg

**Comment by Wattenberger** [comment]
It's not currently documented, but the interactive visualizer does accept tokens. If you add a `token` key into Local Storage with a [PAT](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) with "repo" access, it will use that token for the GitHub API calls.

![image](https://user-images.githubusercontent.com/3506269/128614480-a1b9042c-e4a9-466a-b984-da11580cad8e.png)

**Comment by filipegiusti** [comment]
THIS PROJECT IS SO GREAT! Thanks @Wattenberger 

I tried the token in local storage approach but couldn't get it to work. Has anything change on the interactive visualizer? I searched "token" in the minified code and couldn't find anything.

**Comment by filipegiusti** [comment]
I ended up doing the following:

1. Go to https://github.com/settings/tokens
1. Generate a new token with repo permissions
1. Go to https://octo-repo-visualization.vercel.app/
1. Add the following code to the JS console replacing the TOKEN with your token.
    ```js
    window.originalFetch = window.fetch;
    const modifiedFetch = (resource, init) => window.originalFetch(resource, { ...init, headers: { "Authorization": "token TOKEN" } });
    window.fetch = modifiedFetch;
    ```
1. In the repository input, type any private repository.
