### ISSUE TITLE
Local Visualization

### ISSUE THREAD

**Issue by RilDev** [githubocto/repo-visualizer#36]
Good day,

I found out about this project today and I'm very impressed! It would be a great tool for people on my team (myself included) to get to know quickly code bases we are not familiar with.

But we don't use GitHub in my company.

Is there a way to run this repo-visualizer locally? A bit like what was done here: https://octo-repo-visualization.vercel.app

Thank you!

**Comment by Wattenberger** [comment]
Hey @RilDev, thanks for the kind words! The GitHub Action is basically just running this node script:

https://github.com/githubocto/repo-visualizer/blob/main/src/index.jsx

which gets bundled with this npm command:

https://github.com/githubocto/repo-visualizer/blob/main/package.json#L3

You should be able to get it working outside of GitHub Actions with minor tweaks!

**Comment by RilDev** [comment]
Thank you very much, I'll be trying this out soon !

**Comment by noklam** [comment]
> Thank you very much, I'll be trying this out soon !

@RilDev  Any luck or hints how can we do this?

**Comment by RilDev** [comment]
Hi @noklam I didn't get around to do it yet. You know, stuff happened!

It was starting to weigh on my conscience actually. Like I said I would do it and then didn't. Thanks for this opportunity of actually keeping my word!

I'll be experimenting with it today!

**Comment by noklam** [comment]
@RilDev Thanks :) I am not familiar with node so I am trying to making tweak to it.

https://github.com/githubocto/repo-visualizer/blob/main/src/index.js seems creating the SVG diagram, ideally would love to keep the interactive feature just like https://octo-repo-visualization.vercel.app

**Comment by RilDev** [comment]
Alright, let's get things going!

Here is the fork I'll be pushing my modifications on: https://github.com/RilDev/repo-visualizer

So far I just commented out the Github actions related code and generate the SVG using `yarn build`.

@Wattenberger could you tell me more about the interactive app https://octo-repo-visualization.vercel.app? Is it generated by another project?

**Comment by noklam** [comment]
It looks like it read from GitHub directly, so we need to configure it to
read source code from Local Repository, I am not sure if there are
additional metadata that only exist in GitHub Repo.
Then we also need to figure out how to run the interactive demo.

**Comment by RilDev** [comment]
Hi there @robatwilliams! Thanks for the tips, I was able to get it to work!

I also updated my fork: https://github.com/RilDev/repo-visualizer

Thanks for the help!
