### ISSUE TITLE
Webpage Performance Issues

### ISSUE THREAD

**Issue by zach83** [githubocto/repo-visualizer#37]
It appears that, at least at the front-end side of things, `repo-visualizer` has trouble with generating images live. From scrolling down the page associated with the demo, it would "freeze up". I would like to help if there was a branch showing the source code for the page.

If that is not possible, here are my suggestions:
- _Reduce the height of the page_
- _Have a loading phase_
- _Make a download button/option_
- _Minify the code_

**Comment by Wattenberger** [comment]
I think you're referring to the live tool hosted here: https://octo-repo-visualization.vercel.app/

The freeze is due to loading too many SVG elements to the DOM - the next step is converting the diagram to be drawn on Canvas, I just need to find the time. Thanks for the flag and suggestions!
