### ISSUE TITLE
How to use to find files connections? 

### ISSUE THREAD

**Issue by zthxxx** [githubocto/repo-visualizer#39]
The writeup has a section ["Potential future directions"](https://next.github.com/projects/repo-visualization#potential-future-directions) that say:

> To find these connections, I scanned the contents of each file for import statements, then linked that file with the one it imports from. 

However I cannot find docs of the feature in README or code of the function in this repo.

![image](https://user-images.githubusercontent.com/15135943/147441648-8f60b011-f875-4f91-9ab4-8f0d355b7f49.png)

**Comment by Wattenberger** [comment]
Hi! That code was very rough and is part of a private repo, unfortunately.

**Comment by zthxxx** [comment]
Is there any plan to open the source?  Or will there be any follow-up to this project?

**Comment by Wattenberger** [comment]
There are no current plans for open-sourcing that code or follow up on this project. We're hoping to explore further, but there's nothing concrete planned. Most of the visualization-generating code is within the `/src/Tree.tsx` file in this repo. If you're interested in recreating the connections between files, those were generated by looking at import statements and using SVG paths.

**Comment by zthxxx** [comment]
emmm, okay
