### ISSUE TITLE
Add option to ignore CI runs on commit

### ISSUE THREAD

**Issue by sobolevn** [githubocto/repo-visualizer#7]
Right now there's no need for us to waste quite a lot of CI resources after `diagram.svg` is commited.

Ideally I would want to have `[ci skip]` tag in a diagram commit message.
But, I understand that this might not work for every project, so this looks like good candidate for an option, something like `with: skip_ci: true`

What do you think?

Btw, our diagram: https://wemake-python-stylegui.de/en/latest/pages/api/index.html#overview
🙂

**Comment by Flexicon** [comment]
Yeah for repos with CI, this is a must have! 👍

**Comment by sirwolfgang** [comment]
I just ran into this. 

The current example setup, when combined with user token branch protection bypassing, seems to trigger an endless loop. Which can definitely have some bad effects on subscribed CI/CD pipelines.

**Comment by Wattenberger** [comment]
Great call! I added the ability to set the commit message, which will allow users to add `[ci skip]`. Let me know if this misses a use case!
